version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(go):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(actions):"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(docker):"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(terraform):"
